/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sr.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-05")
public class CurrencyDetails implements org.apache.thrift.TBase<CurrencyDetails, CurrencyDetails._Fields>, java.io.Serializable, Cloneable, Comparable<CurrencyDetails> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CurrencyDetails");

  private static final org.apache.thrift.protocol.TField KOSZT_WALUTA_OBCA_FIELD_DESC = new org.apache.thrift.protocol.TField("kosztWalutaObca", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField KOSZT_WALUTA_RODZIMA_FIELD_DESC = new org.apache.thrift.protocol.TField("kosztWalutaRodzima", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CurrencyDetailsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CurrencyDetailsTupleSchemeFactory();

  public int kosztWalutaObca; // required
  public int kosztWalutaRodzima; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KOSZT_WALUTA_OBCA((short)1, "kosztWalutaObca"),
    KOSZT_WALUTA_RODZIMA((short)2, "kosztWalutaRodzima");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */

    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KOSZT_WALUTA_OBCA
          return KOSZT_WALUTA_OBCA;
        case 2: // KOSZT_WALUTA_RODZIMA
          return KOSZT_WALUTA_RODZIMA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */

    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __KOSZTWALUTAOBCA_ISSET_ID = 0;
  private static final int __KOSZTWALUTARODZIMA_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KOSZT_WALUTA_OBCA, new org.apache.thrift.meta_data.FieldMetaData("kosztWalutaObca", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.KOSZT_WALUTA_RODZIMA, new org.apache.thrift.meta_data.FieldMetaData("kosztWalutaRodzima", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CurrencyDetails.class, metaDataMap);
  }

  public CurrencyDetails() {
  }

  public CurrencyDetails(
    int kosztWalutaObca,
    int kosztWalutaRodzima)
  {
    this();
    this.kosztWalutaObca = kosztWalutaObca;
    setKosztWalutaObcaIsSet(true);
    this.kosztWalutaRodzima = kosztWalutaRodzima;
    setKosztWalutaRodzimaIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CurrencyDetails(CurrencyDetails other) {
    __isset_bitfield = other.__isset_bitfield;
    this.kosztWalutaObca = other.kosztWalutaObca;
    this.kosztWalutaRodzima = other.kosztWalutaRodzima;
  }

  public CurrencyDetails deepCopy() {
    return new CurrencyDetails(this);
  }


  public void clear() {
    setKosztWalutaObcaIsSet(false);
    this.kosztWalutaObca = 0;
    setKosztWalutaRodzimaIsSet(false);
    this.kosztWalutaRodzima = 0;
  }

  public int getKosztWalutaObca() {
    return this.kosztWalutaObca;
  }

  public CurrencyDetails setKosztWalutaObca(int kosztWalutaObca) {
    this.kosztWalutaObca = kosztWalutaObca;
    setKosztWalutaObcaIsSet(true);
    return this;
  }

  public void unsetKosztWalutaObca() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __KOSZTWALUTAOBCA_ISSET_ID);
  }

  /** Returns true if field kosztWalutaObca is set (has been assigned a value) and false otherwise */
  public boolean isSetKosztWalutaObca() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __KOSZTWALUTAOBCA_ISSET_ID);
  }

  public void setKosztWalutaObcaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __KOSZTWALUTAOBCA_ISSET_ID, value);
  }

  public int getKosztWalutaRodzima() {
    return this.kosztWalutaRodzima;
  }

  public CurrencyDetails setKosztWalutaRodzima(int kosztWalutaRodzima) {
    this.kosztWalutaRodzima = kosztWalutaRodzima;
    setKosztWalutaRodzimaIsSet(true);
    return this;
  }

  public void unsetKosztWalutaRodzima() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __KOSZTWALUTARODZIMA_ISSET_ID);
  }

  /** Returns true if field kosztWalutaRodzima is set (has been assigned a value) and false otherwise */
  public boolean isSetKosztWalutaRodzima() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __KOSZTWALUTARODZIMA_ISSET_ID);
  }

  public void setKosztWalutaRodzimaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __KOSZTWALUTARODZIMA_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field,  java.lang.Object value) {
    switch (field) {
    case KOSZT_WALUTA_OBCA:
      if (value == null) {
        unsetKosztWalutaObca();
      } else {
        setKosztWalutaObca((java.lang.Integer)value);
      }
      break;

    case KOSZT_WALUTA_RODZIMA:
      if (value == null) {
        unsetKosztWalutaRodzima();
      } else {
        setKosztWalutaRodzima((java.lang.Integer)value);
      }
      break;

    }
  }


  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case KOSZT_WALUTA_OBCA:
      return getKosztWalutaObca();

    case KOSZT_WALUTA_RODZIMA:
      return getKosztWalutaRodzima();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case KOSZT_WALUTA_OBCA:
      return isSetKosztWalutaObca();
    case KOSZT_WALUTA_RODZIMA:
      return isSetKosztWalutaRodzima();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CurrencyDetails)
      return this.equals((CurrencyDetails)that);
    return false;
  }

  public boolean equals(CurrencyDetails that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_kosztWalutaObca = true;
    boolean that_present_kosztWalutaObca = true;
    if (this_present_kosztWalutaObca || that_present_kosztWalutaObca) {
      if (!(this_present_kosztWalutaObca && that_present_kosztWalutaObca))
        return false;
      if (this.kosztWalutaObca != that.kosztWalutaObca)
        return false;
    }

    boolean this_present_kosztWalutaRodzima = true;
    boolean that_present_kosztWalutaRodzima = true;
    if (this_present_kosztWalutaRodzima || that_present_kosztWalutaRodzima) {
      if (!(this_present_kosztWalutaRodzima && that_present_kosztWalutaRodzima))
        return false;
      if (this.kosztWalutaRodzima != that.kosztWalutaRodzima)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + kosztWalutaObca;

    hashCode = hashCode * 8191 + kosztWalutaRodzima;

    return hashCode;
  }


  public int compareTo(CurrencyDetails other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetKosztWalutaObca()).compareTo(other.isSetKosztWalutaObca());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKosztWalutaObca()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kosztWalutaObca, other.kosztWalutaObca);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKosztWalutaRodzima()).compareTo(other.isSetKosztWalutaRodzima());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKosztWalutaRodzima()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kosztWalutaRodzima, other.kosztWalutaRodzima);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }


  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CurrencyDetails(");
    boolean first = true;

    sb.append("kosztWalutaObca:");
    sb.append(this.kosztWalutaObca);
    first = false;
    if (!first) sb.append(", ");
    sb.append("kosztWalutaRodzima:");
    sb.append(this.kosztWalutaRodzima);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CurrencyDetailsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CurrencyDetailsStandardScheme getScheme() {
      return new CurrencyDetailsStandardScheme();
    }
  }

  private static class CurrencyDetailsStandardScheme extends org.apache.thrift.scheme.StandardScheme<CurrencyDetails> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CurrencyDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KOSZT_WALUTA_OBCA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.kosztWalutaObca = iprot.readI32();
              struct.setKosztWalutaObcaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // KOSZT_WALUTA_RODZIMA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.kosztWalutaRodzima = iprot.readI32();
              struct.setKosztWalutaRodzimaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CurrencyDetails struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(KOSZT_WALUTA_OBCA_FIELD_DESC);
      oprot.writeI32(struct.kosztWalutaObca);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(KOSZT_WALUTA_RODZIMA_FIELD_DESC);
      oprot.writeI32(struct.kosztWalutaRodzima);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CurrencyDetailsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CurrencyDetailsTupleScheme getScheme() {
      return new CurrencyDetailsTupleScheme();
    }
  }

  private static class CurrencyDetailsTupleScheme extends org.apache.thrift.scheme.TupleScheme<CurrencyDetails> {


    public void write(org.apache.thrift.protocol.TProtocol prot, CurrencyDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetKosztWalutaObca()) {
        optionals.set(0);
      }
      if (struct.isSetKosztWalutaRodzima()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetKosztWalutaObca()) {
        oprot.writeI32(struct.kosztWalutaObca);
      }
      if (struct.isSetKosztWalutaRodzima()) {
        oprot.writeI32(struct.kosztWalutaRodzima);
      }
    }


    public void read(org.apache.thrift.protocol.TProtocol prot, CurrencyDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.kosztWalutaObca = iprot.readI32();
        struct.setKosztWalutaObcaIsSet(true);
      }
      if (incoming.get(1)) {
        struct.kosztWalutaRodzima = iprot.readI32();
        struct.setKosztWalutaRodzimaIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

